name: Staging Environment

on:
  pull_request:
    branches: [main]
    paths:
      - 'terraform/environments/staging/**'
      - 'terraform/modules/**'

permissions:
  contents: read
  pull-requests: write
  security-events: write
  id-token: write

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan-reusable.yaml
    with:
      environment: staging
      terraform-dir: terraform/environments/staging
      run-checkov: true
      checkov-frameworks: "cis"
      run-terrascan: true
    secrets: inherit